### ISSUE TITLE
[Request] Need upgrade queue.md add `guarantee`

### ISSUE THREAD

**Issue by samzong** [volcano-sh/website#315]
Volcano support `spec.guarantee` reserve resources for a queue. but document doesn't have tips.

```yaml
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: q1
spec:
  reclaimable: true
  weight: 1
  guarantee:             // reservation key word
    resource:            // specified reserving resource
      cpu: 2c
      memory: 4G
```

> doc

- <https://raw.githubusercontent.com/volcano-sh/volcano/master/docs/design/queue-guarantee-resource-reservation-design.md>
